language: ruby
rvm:
# Note: skip 2.1 onwards
  - "2.0.0"
  - "1.9.3"
  - "1.8.7"
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode
  - rbx-18mode
matrix:
  allow_failures:
    - rvm: "1.8.7"
    - rvm: jruby-head
    - rvm: rbx-19mode
    - rvm: rbx-18mode
